let userAge = 24;
let userName = "Vasia";
let userSurName = "Petkin";
let fullUser = userAge + " " + userName + " " + userSurName;
console.log(fullUser);
let newUser;
let shoppingList;
let userOnline;
let salaryUser;
let cursorCoordinatesUser;
